-- MySQL Script generated by MySQL Workbench
-- Fri Dec 22 15:30:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema petshelter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `petshelter` ;

-- -----------------------------------------------------
-- Schema petshelter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petshelter` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `petshelter` ;

-- -----------------------------------------------------
-- Table `petshelter`.`adopters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshelter`.`adopters` ;

CREATE TABLE IF NOT EXISTS `petshelter`.`adopters` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email_address` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshelter`.`shelters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshelter`.`shelters` ;

CREATE TABLE IF NOT EXISTS `petshelter`.`shelters` (
  `shelter_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `email_address` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`shelter_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshelter`.`pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshelter`.`pets` ;

CREATE TABLE IF NOT EXISTS `petshelter`.`pets` (
  `pet_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `species` VARCHAR(255) NULL DEFAULT NULL,
  `breed` VARCHAR(255) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `gender` VARCHAR(50) NULL DEFAULT NULL,
  `health_status` VARCHAR(255) NULL DEFAULT NULL,
  `behavior` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `shelter_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `shelter_id` (`shelter_id` ASC) VISIBLE,
  CONSTRAINT `pets_ibfk_1`
    FOREIGN KEY (`shelter_id`)
    REFERENCES `petshelter`.`shelters` (`shelter_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshelter`.`adoptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshelter`.`adoptions` ;

CREATE TABLE IF NOT EXISTS `petshelter`.`adoptions` (
  `adoption_id` INT NOT NULL AUTO_INCREMENT,
  `pet_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `adoption_date` DATE NULL DEFAULT NULL,
  `status` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`adoption_id`),
  INDEX `pet_id` (`pet_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `adoptions_ibfk_1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `petshelter`.`pets` (`pet_id`),
  CONSTRAINT `adoptions_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `petshelter`.`adopters` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshelter`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshelter`.`documents` ;

CREATE TABLE IF NOT EXISTS `petshelter`.`documents` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `pet_id` INT NULL DEFAULT NULL,
  `document_type` VARCHAR(100) NULL DEFAULT NULL,
  `document` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`document_id`),
  INDEX `pet_id` (`pet_id` ASC) VISIBLE,
  CONSTRAINT `documents_ibfk_1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `petshelter`.`pets` (`pet_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshelter`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petshelter`.`staff` ;

CREATE TABLE IF NOT EXISTS `petshelter`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `email_address` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `shelter_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `shelter_id` (`shelter_id` ASC) VISIBLE,
  CONSTRAINT `staff_ibfk_1`
    FOREIGN KEY (`shelter_id`)
    REFERENCES `petshelter`.`shelters` (`shelter_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
